/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_translate_jni_BreakpadInit */

#ifndef _Included_com_sogou_translate_jni_BreakpadInit
#define _Included_com_sogou_translate_jni_BreakpadInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sogou_translate_jni_BreakpadInit
 * Method:    initBreakpadNative
 * Signature: (Ljava/lang/String;Lcom/sogou/translate/jni/InfoHelper;)V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_jni_BreakpadInit_initBreakpadNative
  (JNIEnv *, jclass, jstring, jobject);

JNIEXPORT void JNICALL Java_com_sogou_translate_jni_BreakpadInit_go2crash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
